"""Readable scientific conclusions derived from committed validation reports."""
import json


def validation_content(data, figure):
    def plot(stem, caption, alt):
        return figure('validation', {'file': f'results/validation/{stem}.png', 'caption': caption, 'alt': alt})

    def row(snr, family='matched_assumptions', estimator='known_speed'):
        return next(r for r in data['noise_sweep']['rows'] if (r['snr_db'], r['family'], r['estimator']) == (snr, family, estimator))

    low, middle, high = row(20), row(40), row(60)
    wrong_speed = row(40, 'speed_1800')
    source_flexible = row(40, 'source_shift_30m', 'speed_search')
    oracle = data['depth']['oracle_and_roundtrip']
    truth_rows = ''.join(f'<tr><th scope="row">{d} m</th><td>{oracle[str(d)]["oracle_estimate_m"]:.0f} m</td><td>{abs(oracle[str(d)]["oracle_estimate_m"]-d):.0f} m</td></tr>' for d in data['design']['evaluation_depths_m'])
    motion = plot('motion_validation', '<b>Positive control, through a complex image.</b> The right panel verifies phase and sign after focusing and reading a known reflector. The left uses independent noise trials and a separately calibrated 1% threshold. These are favorable resolved targets, not distributed pyramid scattering.', 'Detection fractions for known 1, 2 and 4 Hz motion, and a focused-image phase recovery control')
    depth = plot('depth_recovery', '<b>Unknown depths, separate evaluation.</b> Five evaluation depths are absent from the candidate library. Forward data use a 2.5 m mesh; predictions use a 5 m mesh. Coloured points pass the noise-calibrated detector; grey crosses are rejected best fits. A best-fit depth by itself is not a detection. All panels use 20 dB reflector SNR.', 'Held-out cavity depths versus estimated depths for three prescribed surface displacement scales')
    noise = plot('noise_transition', '<b>Signal strength helps when the model is appropriate.</b> This follow-up sweep holds the reference surface motion at 1 mm and changes receiver SNR. Each level has its own independent null calibration. More precise observations can also make an incorrect physical model confidently wrong. Lines connect tested conditions; they are not measured satellite performance curves.', 'Correctly localized cavities and false alarms across 20, 40 and 60 dB signal-to-noise ratios')
    coupled = plot('coupled_measurement', '<b>The missing link is now simulated.</b> A physical wave solution for a buried cavity modulates seven known surface reflectors. The resulting focused SLC retains the wave-induced phase. Readout assumes those reflectors are separable and their supports are known. No depth formula is used to plant the radar motion.', 'Focused image of seven reflectors and the corresponding physical and recovered displacement at one reflector')
    stress = plot('assumption_stress', '<b>Vary what the estimator assumes.</b> The 20 dB benchmark changes wave speed, cavity radius or source position while keeping the calibration fixed. A speed-search alternative tests whether adding a physical nuisance parameter helps. False alarms and localization must be evaluated together.', 'Depth localization and cavity-free false alarms for matched and mismatched physical assumptions')
    frequency = plot('frequency_depth', '<b>Actual burial depth and source frequency vary independently.</b> All three depths lie inside the fixed model-axis search range. Left: ungated diagnostic peaks from our patch-shift reconstruction. Crosses fail the full ellipse gate. Right: full-gate acceptance. The original wavelength is fixed at 0.48 m; no target-specific rescaling is allowed.', 'Physical depth versus patch-shift model peaks at three source frequencies, with full-gate acceptance counts')
    ambiguity = plot('source_ambiguity', '<b>A conditional ambiguity, with an extra check.</b> At each frequency, a cavity-free model fits unrestricted complex strengths for one, three or seven surface sources. Seven sources can match seven measured complex values. Fourteen additional receiver positions test generalization. This is not an ambient-source probability model or a proposed explanation of the Khafre images.', 'No-cavity source fits at measured and held-out receivers, including the seven-source alternative')
    null = plot('independent_controls', '<b>Independent scenes, complete filter.</b> Thirty-two new stationary scenes preserve the actual correlations introduced by the overlapping filter bank. Separate flanks supply the geometric-median correction. Each image has seven target patches; the image, not every look or pixel, is the independent realization.', 'Ungated fit scores and full-filter acceptance across 32 independent stationary scene realizations')
    gate_count = data['frequency_depth']['accepted_reflectors']
    total = data['frequency_depth']['trials']
    null_count = sum(r['scenes_with_any_gate_pass'] for r in data['independent_controls']['groups'])
    ambiguous8 = next(r for r in data['ambiguity']['rows'] if r['frequency_hz'] == 8 and r['source_count'] == 7 and r['split'] == 'held_out_receivers')
    ambiguous25 = next(r for r in data['ambiguity']['rows'] if r['frequency_hz'] == 25 and r['source_count'] == 7 and r['split'] == 'held_out_receivers')
    convergence = data['depth']['convergence']['cavity_perturbation_correlation']
    table_rows = ''
    labels = {'matched_assumptions': 'Matched assumptions', 'speed_1800': 'Wrong wave speed', 'source_shift_30m': 'Source shifted 30 m'}
    for r in data['noise_sweep']['rows']:
        table_rows += f'<tr><th scope="row">{labels[r["family"]]}</th><td>{r["snr_db"]:.0f}</td><td>{"Fixed speed" if r["estimator"] == "known_speed" else "Speed searched"}</td><td>{r["detection_rate"]:.0%}</td><td>{r["detected_within_20m_rate"]:.0%}</td><td>{r["false_alarm_rate"]:.0%}</td></tr>'
    snippets = {
        'hero_result': f'In a favorable physical model, {high["detected_within_20m_rate"]:.0%} of high-SNR trials locate the cavity within 20 m. At lower SNR, that falls to {low["detected_within_20m_rate"]:.0%}. The result depends on the measurement and the assumptions.',
        'motion_section': f'''<section class="section" id="signal"><div class="wrap">
          <div class="section-heading"><span class="section-number">01 / CAN THE SURFACE MOTION BE MEASURED?</span><h2>Start with a signal<br>we know is there.</h2><p>Controlled experiments have already shown satellite SAR measuring surface vibration. The next question is whether a particular acquisition and processor recover the motion needed for an underground inference.</p></div>
          <div class="published-evidence"><span class="evidence-badge">External measured evidence</span><p>A 2026 study compared satellite SAR with simultaneous ground measurements on vibrating targets. It recovered 1–4 Hz motion with radial RMS amplitudes from 10.43 to 0.10 mm. These were controlled, highly reflective targets. <a href="https://strathprints.strath.ac.uk/95237/">Vattulainen et al., IEEE Access ↗</a></p></div>
          <article id="phase-control" class="research-block"><h3>Our positive control preserves the motion.</h3><p>A known displacement changes the radar phase, passes through a simplified focusing operation, and is recovered from the complex image. The ideal pulse intensity does not change. A failed patch-shift test therefore cannot rule out every way to measure vibration.</p>{motion}
          <div class="scope"><strong>What this establishes</strong><p>The phase channel and its units work in our controlled acquisition. Known reflector positions, independent receiver noise and perfect focusing are favorable assumptions. This is not a field-validated extraction method for distributed stone or soil.</p></div></article>
        </div></section>''',
        'depth_section': f'''<section class="section evidence" id="depth"><div class="wrap">
          <div class="section-heading"><span class="section-number">02 / DOES THE MOTION CONSTRAIN DEPTH?</span><h2>Give depth recovery<br>a fair chance to succeed.</h2><p>A buried cavity now changes a physical wavefield, which changes the complex radar measurement. A fixed physical-template estimator receives the observation and predicts depth. Evaluation depths are withheld from its candidate library.</p></div>
          <ol class="signal-chain"><li><span>01 / Forward model</span><strong>Buried cavity</strong><small>Wave equation; known active source</small></li><li><span>02 / Surface response</span><strong>Seven reflectors move</strong><small>One shared, prescribed amplitude scale</small></li><li><span>03 / Acquisition</span><strong>Complex radar image</strong><small>Phase modulation, focusing and noise</small></li><li><span>04 / Inference</span><strong>Unknown depth estimated</strong><small>Frozen library; separate false-alarm trials</small></li></ol>
          <p class="chain-note">The forward model is independent of the Doppler-to-depth steering formula. The physical-template inverse uses the same wave-equation family on a coarser mesh. It is a favorable reference estimator, not Biondi’s method.</p>
          <div class="result-strip"><article><span class="eyebrow">Noiseless surface waveforms</span><strong>5 / 5</strong><p>Held-out depths recovered within 10 m, the half-step of the candidate grid.</p></article><article><span class="eyebrow">Radar, 20 dB SNR</span><strong>{low['detected_within_20m_rate']:.0%}</strong><p>Detected and localized within 20 m. {low['false_alarm_rate']:.0%} cavity-free false alarms.</p></article><article><span class="eyebrow">Radar, 60 dB SNR</span><strong>{high['detected_within_20m_rate']:.0%}</strong><p>Detected and localized within 20 m. {high['false_alarm_rate']:.0%} observed false alarms in 100 null trials.</p></article></div>
          <p class="small">Radar figures above use the SNR sweep: 1 mm peak cavity-free reference motion, known source and 2,000 m/s rock. Each condition has 100 cavity trials across five depths and 100 null noise trials. They are repeated noise draws on a few physical scenes, not 100 surveyed sites.</p>
          {noise}
          <div class="scope"><strong>Conditional feasibility, with clear limits</strong><p>Depth information survives in this simple model when motion and measurement precision are sufficient and the physical assumptions are appropriate. The supplied amplitudes and SNRs are not measurements at Giza. The model contains a horizontal cylindrical void of 20 m radius, known active excitation and uniform rock. It does not test vertical columns, spiral ramps, kilometre-scale depth or ambient-source recovery.</p></div>
          <div class="scenario-lab" id="scenario-lab"><div><span class="eyebrow">Explore the measured runs</span><h3>What happens when<br>an assumption changes?</h3><p>Choose a tested condition. Results come directly from the saved trials; the controls do not rerun or interpolate the simulation.</p><label for="scenario">Physical condition</label><select id="scenario"><option value="matched_assumptions">Source and rock model match</option><option value="speed_1800">Rock speed is 1,800 instead of 2,000 m/s</option><option value="source_shift_30m">Vibration source is displaced by 30 m</option></select><label for="estimator">Estimator</label><select id="estimator"><option value="known_speed">Assume fixed rock speed</option><option value="speed_search">Search three possible rock speeds</option></select><label for="snr">Reflector SNR <output id="snr-value" for="snr">20 dB</output></label><input id="snr" type="range" min="20" max="60" step="20" value="20"></div>
          <div class="scenario-results" aria-live="polite" aria-atomic="true"><span class="eyebrow">100 cavity trials · 100 null trials</span><div class="scenario-metric"><span>Detected and within 20 m</span><strong id="scenario-localized">{low['detected_within_20m_rate']:.0%}</strong><meter id="localized-meter" min="0" max="1" value="{low['detected_within_20m_rate']}" aria-label="Fraction detected and localized"></meter></div><div class="scenario-metric"><span>Cavity-free false alarms</span><strong id="scenario-false-alarm">{low['false_alarm_rate']:.0%}</strong><meter id="false-alarm-meter" min="0" max="1" value="{low['false_alarm_rate']}" aria-label="False alarm fraction"></meter></div><p id="scenario-interval" class="small">False-alarm interval: {low['false_alarm_ci'][0]:.1%}–{low['false_alarm_ci'][1]:.1%} (95% Wilson).</p><p id="scenario-interpretation">Low noise-calibrated recovery in this tested condition.</p><p class="small">Intervals describe receiver-noise sampling under these fixed models. Zero observed false alarms does not mean zero risk.</p></div></div>
          <details class="technical"><summary>All SNR results, including the speed-search alternative <span aria-hidden="true">+</span></summary><p>With the wrong wave speed at 40 dB, the fixed-speed model falsely accepts {wrong_speed['false_alarm_rate']:.0%} of cavity-free trials. With an unmodelled source shift, the speed-search model has both {source_flexible['detected_within_20m_rate']:.0%} localization and {source_flexible['false_alarm_rate']:.0%} false alarms. A high positive hit rate alone is insufficient.</p><div class="table-scroll" tabindex="0" role="region" aria-label="SNR and physical assumption results"><table><thead><tr><th>Condition</th><th>SNR / dB</th><th>Estimator</th><th>Detected</th><th>Detected within 20 m</th><th>False alarms</th></tr></thead><tbody>{table_rows}</tbody></table></div></details>
          <details class="support-detail"><summary>Inspect the coupled image, amplitude sweep and noiseless control <span aria-hidden="true">+</span></summary><div class="detail-inner">{coupled}{depth}{stress}<h3>Noiseless reference estimates</h3><div class="table-scroll" tabindex="0" role="region" aria-label="Noiseless depth recovery"><table><thead><tr><th>True depth</th><th>Estimated depth</th><th>Absolute error</th></tr></thead><tbody>{truth_rows}</tbody></table></div><p>The fine/coarse cavity-perturbation correlation is {convergence:.3f}. Numerical mismatch is present and remains in evaluation. Source gain is fitted; source location and timing are assumed known. The depth grid is fixed at 20 m spacing.</p><p>Each detector threshold uses 300 separate cavity-free trials at a nominal 1% level. The SNR extension follows the initial 20 dB amplitude study and uses separate seeds. These are documented exploratory benchmarks, not a formally preregistered field trial.</p></div></details>
          <p class="resource-links"><a href="data/validation_metrics.json" download>All benchmark results ↓</a><a href="data/validation_design.json" download>Design &amp; assumptions ↓</a><a href="data/validation_snr_trials.csv" download>SNR trial records ↓</a><a href="data/validation_depth_trials.csv" download>Depth trial records ↓</a></p>
        </div></section>''',
        'identifiability_section': f'''<section class="section" id="ambiguity"><div class="wrap"><div class="section-heading"><span class="section-number">03 / IS DEPTH THE ONLY EXPLANATION?</span><h2>Test the alternatives<br>that can look convincing.</h2><p>A repeatable feature can still come from surface scattering or an incorrect source model. These tests change the possible explanation while holding other parts of the experiment fixed.</p></div>
          <article class="research-block"><span class="eyebrow">Physical source × physical depth</span><h3>Does the processing follow the buried object?</h3><p>We independently vary cavity depth and excitation frequency, then run the coupled radar images through our patch-shift reconstruction. The model wavelength stays fixed. Its full filter accepts <strong>{gate_count} of {total}</strong> reflector observations from nine moving scenes.</p>{frequency}<div class="scope"><strong>What this means</strong><p>This reconstruction has not demonstrated sensitivity to these physical cavity signals. The ungated peaks are diagnostic outputs only. These SH waves have one displacement polarization; the ellipse filter demands a two-axis registration trajectory. Its rejection of these inputs does not establish sensitivity to richer elastic motion. Rejecting static controls alone does not establish a useful cavity detector.</p></div></article>
          <article class="research-block"><span class="eyebrow">Unknown excitation</span><h3>Could a different source imitate the cavity?</h3><p>At one frequency, seven unconstrained surface sources in cavity-free rock can reproduce the seven measured complex displacements from a cavity. At fourteen additional receivers, mismatch is {ambiguous8['relative_complex_misfit']:.1%} at 8 Hz and {ambiguous25['relative_complex_misfit']:.1%} at 25 Hz. Extra measurements can expose the alternative.</p>{ambiguity}<div class="scope"><strong>A limited non-uniqueness result</strong><p>The fitted source weights are free to vary in amplitude and phase. This does not establish that such sources exist at Khafre. It shows why source constraints, multiple frequencies and independent locations matter before a sparse vibration pattern is assigned a unique underground shape.</p></div></article>
          <p class="resource-links"><a href="data/validation_frequency_depth_trials.csv" download>Depth × frequency trials ↓</a><a href="data/validation_ambiguity_trials.csv" download>Alternative-source fits ↓</a></p>
        </div></section>''',
        'independent_section': f'''<div class="research-block"><h3>Independent static scenes, with the full rule.</h3><p>The corrected per-window filter accepts no target in {data['independent_controls']['scene_count']} independent stationary scenes ({null_count} scenes with a pass). It also rejects the moving-reflector examples above. These two outcomes must be read together.</p>{null}<p class="small">Each class has only 16 independent images; zero passing scenes gives a 95% Wilson upper bound of about {data['independent_controls']['groups'][0]['scene_pass_ci'][1]:.0%} for that scene-level rate. This is not a zero false-alarm guarantee. Original T1–T7 images are additional mechanism and sensitivity studies, not independent field trials.</p></div>''',
        'scenario_data': json.dumps(data['noise_sweep']['rows'], allow_nan=False).replace('<', '\\u003c'),
    }
    return snippets
